/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberRouteImport } from './routes/ueber'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CouchesIndexRouteImport } from './routes/couches.index'
import { Route as CouchesIdRouteImport } from './routes/couches.$id'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as AuthenticatedCheckoutIdRouteImport } from './routes/_authenticated/checkout.$id'

const UeberRoute = UeberRouteImport.update({
  id: '/ueber',
  path: '/ueber',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouchesIndexRoute = CouchesIndexRouteImport.update({
  id: '/couches/',
  path: '/couches/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouchesIdRoute = CouchesIdRouteImport.update({
  id: '/couches/$id',
  path: '/couches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutIdRoute = AuthenticatedCheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/ueber': typeof UeberRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/couches/$id': typeof CouchesIdRoute
  '/couches/': typeof CouchesIndexRoute
  '/checkout/$id': typeof AuthenticatedCheckoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/ueber': typeof UeberRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/couches/$id': typeof CouchesIdRoute
  '/couches': typeof CouchesIndexRoute
  '/checkout/$id': typeof AuthenticatedCheckoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontakt': typeof KontaktRoute
  '/ueber': typeof UeberRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/couches/$id': typeof CouchesIdRoute
  '/couches/': typeof CouchesIndexRoute
  '/_authenticated/checkout/$id': typeof AuthenticatedCheckoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/ueber'
    | '/konto'
    | '/couches/$id'
    | '/couches/'
    | '/checkout/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kontakt'
    | '/ueber'
    | '/konto'
    | '/couches/$id'
    | '/couches'
    | '/checkout/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kontakt'
    | '/ueber'
    | '/_authenticated/konto'
    | '/couches/$id'
    | '/couches/'
    | '/_authenticated/checkout/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KontaktRoute: typeof KontaktRoute
  UeberRoute: typeof UeberRoute
  CouchesIdRoute: typeof CouchesIdRoute
  CouchesIndexRoute: typeof CouchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber': {
      id: '/ueber'
      path: '/ueber'
      fullPath: '/ueber'
      preLoaderRoute: typeof UeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couches/': {
      id: '/couches/'
      path: '/couches'
      fullPath: '/couches/'
      preLoaderRoute: typeof CouchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couches/$id': {
      id: '/couches/$id'
      path: '/couches/$id'
      fullPath: '/couches/$id'
      preLoaderRoute: typeof CouchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$id': {
      id: '/_authenticated/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof AuthenticatedCheckoutIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
  AuthenticatedCheckoutIdRoute: typeof AuthenticatedCheckoutIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
  AuthenticatedCheckoutIdRoute: AuthenticatedCheckoutIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KontaktRoute: KontaktRoute,
  UeberRoute: UeberRoute,
  CouchesIdRoute: CouchesIdRoute,
  CouchesIndexRoute: CouchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
